name: Update GitHub Contribution Chart

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate contribution chart
        uses: pipipi-dev/gcchart@v1
        with:
          outputs: |
            contributions-lifetime.svg?period=10000&granularity=month&style=clean&theme=dark&cumulative=true
